### ISSUE TITLE
Calculating the OM rate Not working

### ISSUE THREAD

**Issue by torv72** [torv72/torv-reports-v4#44]
I was writing a report for Maroon Creek Club.  In their particular case I wanted to calculate the organic matter rate.  When I answer "yes" to the question, nothing happens.  In the past, additional questions would appear asking for additional data in order to make the calculations.  The results would then appear in the Organic Matter section.  

FYI.  Most of the time I answer No to the question.  Unfortunately many of my clients do not provide me with the information I need to make these calculations.  The calculations that I use to do this came from a Shiny App and was incorporated into this report.  I wanted to preserve these calculations in case the Shiny App ever disappeared from where I got it from.  

In this case, I went to the Shiny App on the web and manually made the calculations and included it in the report.

Do you have any recommendations on how to handle this going forward?  I don't know that it will be utilized a lot but I like having the ability to make the calculations if I need to.  If we were to remove this from the report entirely, is there a way to preserve the Shiny App just in case I were to need it to make calculations in case they come up with certain clients?  I would then need to manually add the results to the report's txt file.  I'd be ok with that.

**Comment by z3tt** [comment]
Thanks for the note. That likely happened when I streamlined the input dialogue for `generate_report()`. Since I never choose this option, it seems to have slipped through. I am going to investigate it.

**Comment by z3tt** [comment]
Should be fixed, please test.

I also streamlined the logic: in case of multiple sampling types it asks once more generally if any accumulation rates should be calculated and, if `y`, asks for each sampling type independently, to avoid multiple questions even if no rates should be calculated overall.

**Comment by torv72** [comment]
It looks like you got it working again.  When I answered “yes” it asked me the questions to perform the calculations.  I wasn’t able to render the report yet because of that flextable error that I’m still getting.  I know you’re working on it.  So once that’s fixed, I’ll give it another try.

FYI that base error seems to be resolved.  Not getting that anymore after you pushed a solution.
